name: Unit test and coverage
on: [pull_request]
jobs:
  coverage:
    runs-on: ubuntu-16.04

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - name: Install Sundials
      run: |
        sudo apt-get install libsundials-serial-dev

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install -r requirements/setup.txt

    - name: Build and install
      run: |
        python -m pip install .[test]

    - name: Unit & coverage tests
      run: |
        python -m pytest --cov --cov-config=.coveragerc

    - name: Submit report to codecov
      uses: codecov/codecov-action@v1
      if: success()

