name: Style
on: [pull_request]
jobs:
  style:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - name: Install tools
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install flake8

    - name: Check code style
      run: |
        python --version
        python -m flake8 --version
        python -m flake8

